version: '2'

services:
  chat:
    image: eng-center-registry.cn-shanghai.cr.aliyuncs.com/public/vinci-chat:latest
    container_name: chat
    build:
      context: ./vinci-inference
      dockerfile: docker/Dockerfile
    ports:
      - '18081:18081'
    environment:
      - CUDA_VISIBLE_DEVICES=1,2
      - access_key=minio_admin
      - access_key_secret=minio_admin
      - endpoint=minio:9000
      - bucket=vinci
      - cdn=http://${CANDIDATE}:19000/vinci
    restart: always
    networks:
      - vinci_local

  retrieval:
    image: eng-center-registry.cn-shanghai.cr.aliyuncs.com/public/vinci-retrieval:latest
    container_name: retrieval
    build:
      context: ./vinci-retrieval
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '18082:18082'
    environment:
      config_path: /opt/worker/app/config.yaml
      oss__access_key: minio_admin
      oss__access_key_secret: minio_admin
      oss__endpoint: minio:9000
      oss__bucket: vinci
      oss__cdn: http://${CANDIDATE}:19000/vinci
    networks:
      - vinci_local

  srs:
    image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5
    container_name: srs
    restart: always
    ports:
      - '1935:1935'
      - '18080:8080'
      - '18081:8081/udp'
      - "1985:1985"
    volumes:
      - ./srs/conf/:/usr/local/srs/vinci/
    environment:
      - CANDIDATE=${CANDIDATE}
    command: ./objs/srs -c vinci/vinci.conf
    privileged: true
    networks:
      - vinci_local

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - '13306:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.cache/mysql/data:/bitnami/mysql/data
    environment:
      - BITNAMI_DEBUG=true
      - TZ=Asia/Shanghai
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_COLLATE=utf8mb4_general_ci
      - MYSQL_ROOT_PASSWORD=123456
    privileged: true
    networks:
      - vinci_local

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_admin
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - .cache/minio:/data
      - ./minio/entry.sh:/usr/local/bin/entry.sh
    networks:
      - vinci_local
    entrypoint:  /bin/sh -c "/usr/local/bin/entry.sh"

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx
    ports:
      - "19333:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - vinci_local
    depends_on:
      - vinci-be
      - vinci-fe

  vinci-be:
    image: eng-center-registry.cn-shanghai.cr.aliyuncs.com/public/vinci-be:latest
    container_name: vinci-be
    build:
      context: ./vinci-be
      dockerfile: Dockerfile
    restart: always
    environment:
      - env=private
      - srs_lb_host=${CANDIDATE}
      - srs_host=srs
      - rtmp_port=1935
      - webrtc_port=18080
      - api_port=8080
      - api_auth_token=cGpsYWI6UFpNdmM4VWhKN3hNQ2JlTQ==
      - internal_app_name=internal
      - mysql_host=mysql:3306
      - mysql_user=root
      - mysql_password=123456
      - oss_access_key_id=minio_admin
      - oss_access_key_secret=minio_admin
      - oss_endpoint=minio:9000
      - oss_bucket=vinci
      - oss_external_endpoint=http://${CANDIDATE}:19000
      - intern_endpoint=http://chat:18081
      - retrieval_endpoint=http://retrieval:18082
      - speech_language=en-US
      - tts=0
      - puyu_base_url=https://puyu.openxlab.org.cn/puyu/api/v1/
      - puyu_api_key=eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiI1MDE4MjM4OSIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTcyNDEyMjk3MCwiY2xpZW50SWQiOiJtcXprcGxtbnc5N29wa28zNmpxaiIsInBob25lIjoiIiwidXVpZCI6IjYzNTgxOTg0LTUzYjctNDAwMS1hYzJlLTBmOTFlMTc3ZDFkYyIsImVtYWlsIjoidmluY2lAcGpsYWIub3JnLmNuIiwiZXhwIjoxODgxODAyOTcwfQ.E01dyrnLZZgaPTD9dtrtXtnl_wkXYb3BHbaHQYnjN89RkdP88r7FY7VxeszW9ujk-913XurIc2e9ngbZCFbh2w
    ports:
      - '18000:8000'
    privileged: true
    networks:
      - vinci_local

  vinci-fe:
    image: eng-center-registry.cn-shanghai.cr.aliyuncs.com/public/vinci-fe:latest
    container_name: vinci-fe
    build:
      context: ./vinci-fe
      dockerfile: deploy/Dockerfile
      args:
        deployDir: deploy
    restart: always
    ports:
      - '19330:80'
    privileged: true
    networks:
      - vinci_local

networks:
  vinci_local:
    driver: bridge
